KPMP/portal-ui

src/packages/@ncigdc/routes/RedirectRoute.js, src/packages/@ncigdc/routes/index.js
=> Kpmp 1654 redirect to repo

src/features.json, src/packages/@ncigdc/containers/RepositoryPage.js
=> Kpmp 1620 hide cases tab

src/packages/@ncigdc/components/TableActions.tsx, src/packages/@ncigdc/containers/RepositoryPage.js
=> KPMP-1671: Use downloadable switch

src/features.json, src/packages/@ncigdc/components/Header.js
=> KPMP-1672: Add cart switch

src/packages/@ncigdc/containers/RepositoryPage.js
=> KPMP-1670: Feature switch on file calc

src/features.json, src/packages/@ncigdc/components/TabPieCharts/RepoFilesPies.js
=> KPMP-1623: Toggle pies, comment out show more

src/features.json, src/packages/@ncigdc/modern_components/FilesTable/FilesTable.model.js
=> Kpmp 1622 turn off linking

package-lock.json
=> KPMP-1614: NPM audit fix

src/packages/@ncigdc/components/TabPieCharts/RepoFilesPies.js
=> KPMP-1623: remove pesky commas

src/packages/@ncigdc/modern_components/FilesTable/FilesTable.model.js
=> KPMP-1622: Remove link from file UUID too

package-lock.json, package.json
=> KPMP-1614: Upgrade scripts

package-lock.json, package.json, src/Root.js, src/packages/@ncigdc/components/DownloadButtonSingle.js
=> KPMP-1683: Add Google Analytics

src/features.json, src/packages/@ncigdc/components/ActionsRow.js
=> KPMP-1691: Add switch to cart button

src/packages/@ncigdc/components/DownloadButtonSingle.js
=> Kpmp 1727 download button delay

src/packages/@ncigdc/components/DownloadFileSingle.js
=> KPMP-1775: Add another button

src/packages/@ncigdc/components/DownloadFileSingle.js
=> Kpmp 1776 request access button

src/packages/@ncigdc/components/DownloadFileSingle.js
=> KPMP-1776: UPdate link

src/packages/@ncigdc/components/DownloadFileSingle.js
=> KPMP-1817: update controlled access text

src/packages/@ncigdc/components/DownloadFileSingle.js
=> KPMP-1817: update controlled access text take 2

src/packages/@ncigdc/components/DownloadButtonSingle.js
=> Kpmp 1881 minio frontend

data/elastic_search_index.txt, data/schema.graphql, src/packages/@ncigdc/components/DownloadButtonSingle.js, src/packages/@ncigdc/modern_components/FilesTable/FilesTable.relay.js
=> Kpmp 1930 files to s3

src/Root.js, src/features.json
=> Kpmp 1991 remove alert

src/packages/@ncigdc/modern_components/CaseAggregations/CaseAggregations.js
=> KPMP_2006: New filter names

data/schema.graphql, src/packages/@ncigdc/modern_components/FileAggregations/FileAggregations.js, src/packages/@ncigdc/modern_components/FileAggregations/FileAggregations.relay.js, src/packages/@ncigdc/modern_components/FilesTable/FilesTable.model.js, src/packages/@ncigdc/modern_components/FilesTable/FilesTable.relay.js
=> KPMP-2010: Add Workflow Type to filter and table

data/staging-db/03-add-redcap-id.sql
=> KPMP-2298: Add SQL

data/staging-db/2311-add-sunsetted-files.sql, package-lock.json, package.json, src/features.json, src/packages/@ncigdc/dux/bannerNotification.js, src/packages/@ncigdc/uikit/Banner.js
=> KPMP-2303: Add new banner

package.json, public/index.html, src/Portal.js, src/packages/@ncigdc/components/Nav/NavBar.js
=> KPMP-2368: Fix css hopefully take 3

src/packages/@ncigdc/theme/global.css
=> KPMP-2368: banner was peeking out

public/index.html
=> Remove IE Check

src/packages/@ncigdc/modern_components/FileAggregations/FileAggregations.js
=> Kpmp 3175 doi update to DOIs
